#!/bin/sh
# gitea-init.sh — Phase 2 init script
# Generated by wirectl on 2026-03-22.
# Components: Harbor, Gitea, OpenBao, Crossplane, ArgoCD
#
# Runs inside the init Job (hook weight 0).
# Writes clusterfactory-wiring-tokens Secret at the end (handoff to Phase 3).

set -e
apk add -q jq

# ── Environment detection ──────────────────────────────────────────────────────
echo "=== [0] Detecting cluster environment ==="

# Allow forcing a specific environment for local testing without a real cloud cluster:
#   helm upgrade clusterfactory . --set-string debugForceEnv=eks
CLUSTER_ENV="${DEBUG_FORCE_ENV:-}"

if [ -z "$CLUSTER_ENV" ]; then
  PROVIDER_ID=$(kubectl get nodes -o jsonpath='{.items[0].spec.providerID}' 2>/dev/null || echo "")

  if echo "$PROVIDER_ID" | grep -q "^aws:"; then
    CLUSTER_ENV="eks"
  elif echo "$PROVIDER_ID" | grep -q "^azure:"; then
    CLUSTER_ENV="aks"
  elif echo "$PROVIDER_ID" | grep -q "^gce:"; then
    CLUSTER_ENV="gke"
  elif echo "$PROVIDER_ID" | grep -qi "docker\|desktop"; then
    CLUSTER_ENV="docker-desktop"
  elif kubectl get nodes -o jsonpath='{.items[0].metadata.labels}' \
       2>/dev/null | grep -q "kubernetes.docker.internal"; then
    CLUSTER_ENV="docker-desktop"
  else
    API_URL=$(kubectl get secret "${KUBECONFIG_SECRET}" -n "${NS}" \
      -o jsonpath='{.data.kubeconfig}' 2>/dev/null | base64 -d \
      | grep "server:" | awk '{print $2}' | head -1 || echo "")
    if echo "$API_URL" | grep -qE "127\.0\.0\.1|localhost"; then
      CLUSTER_ENV="local"
    else
      CLUSTER_ENV="remote"
    fi
  fi
fi

echo "  Detected environment: $CLUSTER_ENV"

# Detect if LoadBalancer services work.
# On Docker Desktop and kind, LoadBalancer stays Pending — use NodePort.
HAS_LB="false"
if [ "$CLUSTER_ENV" = "eks" ] || [ "$CLUSTER_ENV" = "aks" ] || [ "$CLUSTER_ENV" = "gke" ]; then
  HAS_LB="true"
fi

# Detect default StorageClass
HAS_STORAGECLASS=$(kubectl get storageclass \
  -o jsonpath='{.items[?(@.metadata.annotations.storageclass\.kubernetes\.io/is-default-class=="true")].metadata.name}' \
  2>/dev/null || echo "")
[ -n "$HAS_STORAGECLASS" ] && HAS_PERSISTENT="true" || HAS_PERSISTENT="false"

echo "  LoadBalancer available : $HAS_LB"
echo "  Default StorageClass   : ${HAS_STORAGECLASS:-none}"

# ── Compute external URLs ──────────────────────────────────────────────────────
if [ "$HAS_LB" = "true" ]; then
  echo "  Waiting for Gitea LoadBalancer IP..."
  GITEA_EXT_IP=""
  for i in $(seq 1 60); do
    GITEA_EXT_IP=$(kubectl get svc "${RELEASE_NAME}-gitea-http" -n "${NS}" \
      -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")
    [ -n "$GITEA_EXT_IP" ] && break
    sleep 5
  done
  GITEA_ROOT_URL="http://${GITEA_EXT_IP}:3000"

  echo "  Waiting for Harbor LoadBalancer IP..."
  HARBOR_EXT_IP=""
  for i in $(seq 1 60); do
    HARBOR_EXT_IP=$(kubectl get svc "${RELEASE_NAME}-harbor" -n "${NS}" \
      -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")
    [ -n "$HARBOR_EXT_IP" ] && break
    sleep 5
  done
  HARBOR_EXT_URL="http://${HARBOR_EXT_IP}"
else
  # NodePort — discover the actual assigned port from the running service
  GITEA_PORT=$(kubectl get svc "${RELEASE_NAME}-gitea-http" -n "${NS}" \
    -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || echo "30080")
  HARBOR_PORT=$(kubectl get svc "${RELEASE_NAME}-harbor" -n "${NS}" \
    -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null || echo "30002")
  GITEA_ROOT_URL="http://${HOST}:${GITEA_PORT}"
  HARBOR_EXT_URL="http://${HOST}:${HARBOR_PORT}"
fi

echo "  Gitea external URL  : $GITEA_ROOT_URL"
echo "  Harbor external URL : $HARBOR_EXT_URL"

GITEA_URL="http://${RELEASE_NAME}-gitea-http.${NS}.svc.cluster.local:3000"
GITEA_USER="${GITEA_USER}"
GITEA_PASSWORD="${GITEA_PASSWORD}"
HARBOR_URL="http://${RELEASE_NAME}-harbor-core.${NS}.svc.cluster.local"
HARBOR_PASSWORD="${HARBOR_PASSWORD}"
OPENBAO_ADDR="http://${RELEASE_NAME}-openbao.${NS}.svc.cluster.local:8200"
ARGOCD_SERVER="http://${RELEASE_NAME}-argocd-server.${NS}.svc.cluster.local:8080"

# ╔══════════════════════════════════════════════════════════════════════╗
# ║  READINESS GATE — wait for all 6 components in order               ║
# ║  Nothing starts until every service is up.                         ║
# ╚══════════════════════════════════════════════════════════════════════╝
_wait() {
  local name="$1" url="$2" retries="${3:-120}" delay="${4:-5}"
  printf "  ○ %-42s" "${name}"
  for i in $(seq 1 "${retries}"); do
    curl -sf --max-time 3 "${url}" > /dev/null 2>&1 && { echo "● READY"; return 0; }
    [ $((i % 12)) -eq 0 ] && printf "\n    still waiting... (%ds elapsed)\n  ○ %-42s" "$((i * delay))" "${name}"
    sleep "${delay}"
  done
  echo "✗ TIMED OUT after $((retries * delay))s — aborting"
  exit 1
}
_wait_auth() {
  local name="$1" url="$2" user="$3" pass="$4" retries="${5:-120}" delay="${6:-5}"
  printf "  ○ %-42s" "${name}"
  for i in $(seq 1 "${retries}"); do
    curl -sf --max-time 3 -u "${user}:${pass}" "${url}" > /dev/null 2>&1 && { echo "● READY"; return 0; }
    [ $((i % 12)) -eq 0 ] && printf "\n    still waiting... (%ds elapsed)\n  ○ %-42s" "$((i * delay))" "${name}"
    sleep "${delay}"
  done
  echo "✗ TIMED OUT after $((retries * delay))s — aborting"
  exit 1
}

echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║  clusterfactory — readiness gate                                    ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""

# 1. OpenBao — secrets must be writable before anything else
_wait      "1/6  OpenBao   — secrets"       "${OPENBAO_ADDR}/v1/sys/health"

# 2. Gitea — source of truth for repo, tokens, runner
_wait      "2/6  Gitea     — git + CI"      "${GITEA_URL}/api/healthz"

# 3. Harbor core — registry must be up before project creation
_wait_auth "3/6  Harbor    — registry"      "${HARBOR_URL}/api/v2.0/ping" "admin" "${HARBOR_PASSWORD}"

# 4. ArgoCD server — must be up to read initial admin secret
_wait      "4/6  ArgoCD    — GitOps"        "${ARGOCD_SERVER}/healthz"

# 5. Crossplane — check pod running
printf "  ○ %-42s" "5/6  Crossplane — cloud resources"
for i in $(seq 1 120); do
  POD=$(kubectl get pods -n "${NS}" -l app=crossplane \
    --field-selector=status.phase=Running -o name 2>/dev/null | head -1)
  [ -n "${POD}" ] && { echo "● READY"; break; }
  [ "${i}" -eq 120 ] && { echo "✗ TIMED OUT — aborting"; exit 1; }
  [ $((i % 12)) -eq 0 ] && printf "\n    still waiting... (%ds elapsed)\n  ○ %-42s" "$((i * 5))" "5/6  Crossplane — cloud resources"
  sleep 5
done

# 6. ArgoCD initial-admin-secret
printf "  ○ %-42s" "6/6  ArgoCD    — admin secret"
for i in $(seq 1 60); do
  SECRET=$(kubectl get secret argocd-initial-admin-secret -n "${NS}" \
    -o jsonpath='{.data.password}' 2>/dev/null || true)
  [ -n "${SECRET}" ] && { echo "● READY"; break; }
  [ "${i}" -eq 60 ] && { echo "✗ TIMED OUT — aborting"; exit 1; }
  [ $((i % 12)) -eq 0 ] && printf "\n    still waiting... (%ds elapsed)\n  ○ %-42s" "$((i * 5))" "6/6  ArgoCD    — admin secret"
  sleep 5
done

echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                                                                      ║"
echo "║   ●  1/6  OpenBao      ●  2/6  Gitea      ●  3/6  Harbor           ║"
echo "║   ●  4/6  ArgoCD       ●  5/6  Crossplane  ●  6/6  ArgoCD secret   ║"
echo "║                                                                      ║"
echo "║                     ALL SYSTEMS READY                                ║"
echo "║                                                                      ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""

# ── OpenBao init + unseal (standalone mode) ───────────────────────────────────
echo "=== Initializing OpenBao ==="
OPENBAO_INITIALIZED=$(curl -sf "${OPENBAO_ADDR}/v1/sys/health" 2>/dev/null | jq -r '.initialized // false' || echo "false")

if [ "$OPENBAO_INITIALIZED" = "false" ]; then
  echo "  Running first-time init..."
  INIT_RESP=$(curl -sf -X POST "${OPENBAO_ADDR}/v1/sys/init" \
    -H "Content-Type: application/json" \
    -d '{"secret_shares":1,"secret_threshold":1}')
  UNSEAL_KEY=$(echo "$INIT_RESP" | jq -r '.keys[0]')
  ROOT_TOKEN=$(echo "$INIT_RESP" | jq -r '.root_token')
  kubectl create secret generic "${RELEASE_NAME}-openbao-init" \
    --namespace "${NS}" \
    --from-literal=unseal_key="${UNSEAL_KEY}" \
    --from-literal=root_token="${ROOT_TOKEN}" \
    --dry-run=client -o yaml | kubectl apply -f -
  curl -sf -X POST "${OPENBAO_ADDR}/v1/sys/unseal" \
    -H "Content-Type: application/json" \
    -d "{\"key\":\"${UNSEAL_KEY}\"}" > /dev/null
  OPENBAO_TOKEN="${ROOT_TOKEN}"
  echo "  OpenBao initialized and unsealed."
else
  echo "  OpenBao already initialized — reading stored credentials."
  OPENBAO_TOKEN=$(kubectl get secret "${RELEASE_NAME}-openbao-init" \
    -n "${NS}" -o jsonpath='{.data.root_token}' 2>/dev/null | base64 -d || echo "")
  SEALED=$(curl -sf "${OPENBAO_ADDR}/v1/sys/health" 2>/dev/null | jq -r '.sealed // true')
  if [ "$SEALED" = "true" ] && [ -n "$OPENBAO_TOKEN" ]; then
    UNSEAL_KEY=$(kubectl get secret "${RELEASE_NAME}-openbao-init" \
      -n "${NS}" -o jsonpath='{.data.unseal_key}' | base64 -d)
    curl -sf -X POST "${OPENBAO_ADDR}/v1/sys/unseal" \
      -H "Content-Type: application/json" \
      -d "{\"key\":\"${UNSEAL_KEY}\"}" > /dev/null
    echo "  OpenBao unsealed."
  fi
fi

# ── 1. Create demo repo ────────────────────────────────────────────────────
echo "=== [2] Creating demo repo ==="
curl -sf -X POST "${GITEA_URL}/api/v1/user/repos" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" \
  -H "Content-Type: application/json" \
  -d '{"name":"clusterfactory-demo","description":"clusterfactory demo repo","auto_init":true,"default_branch":"main"}' \
  > /dev/null || echo "  (repo may already exist)"
# ── 3. Push seed files ──────────────────────────────────────────────────────
echo "=== [3] Pushing seed files to demo repo ==="
_push_file() {
  local repo_path="$1"
  local local_path="$2"
  local msg="$3"
  local content
  content=$(base64 -w0 "${local_path}")
  curl -sf -X POST "${GITEA_URL}/api/v1/repos/${GITEA_USER}/clusterfactory-demo/contents/${repo_path}" \
    -u "${GITEA_USER}:${GITEA_PASSWORD}" \
    -H "Content-Type: application/json" \
    -d "{\"message\":\"${msg}\",\"content\":\"${content}\"}" \
    > /dev/null || echo "  (${repo_path} may already exist)"
}

# CI workflow
_push_file ".gitea/workflows/ci.yaml" "/scripts/ci.yaml" "feat: add CI workflow"

# Crossplane configure-cloud workflow (flat key name from ConfigMap)
_push_file ".gitea/workflows/configure-cloud.yaml" "/scripts/crossplane-configure-cloud.yaml" "feat: add configure-cloud workflow"

# Crossplane providers in deploy/ (ArgoCD syncs these automatically)
_push_file "deploy/crossplane/provider-aws.yaml"   "/scripts/crossplane-provider-aws.yaml"   "feat: add AWS Crossplane provider"
_push_file "deploy/crossplane/provider-azure.yaml" "/scripts/crossplane-provider-azure.yaml" "feat: add Azure Crossplane provider"
_push_file "deploy/crossplane/provider-gcp.yaml"   "/scripts/crossplane-provider-gcp.yaml"   "feat: add GCP Crossplane provider"

# Crossplane ProviderConfig templates + examples
_push_file "crossplane/aws/providerconfig.yaml"    "/scripts/crossplane-aws-providerconfig.yaml"    "feat: add AWS ProviderConfig template"
_push_file "crossplane/aws/credentials.conf"       "/scripts/crossplane-aws-credentials.conf"       "feat: add AWS credentials template"
_push_file "crossplane/aws/example-bucket.yaml"    "/scripts/crossplane-aws-example-bucket.yaml"    "feat: add AWS S3 bucket example"
_push_file "crossplane/azure/providerconfig.yaml"  "/scripts/crossplane-azure-providerconfig.yaml"  "feat: add Azure ProviderConfig template"
_push_file "crossplane/azure/credentials.json"     "/scripts/crossplane-azure-credentials.json"     "feat: add Azure credentials template"
_push_file "crossplane/azure/example-storage.yaml" "/scripts/crossplane-azure-example-storage.yaml" "feat: add Azure storage example"
_push_file "crossplane/gcp/providerconfig.yaml"    "/scripts/crossplane-gcp-providerconfig.yaml"    "feat: add GCP ProviderConfig template"
_push_file "crossplane/gcp/credentials.json"       "/scripts/crossplane-gcp-credentials.json"       "feat: add GCP credentials template"
_push_file "crossplane/gcp/example-bucket.yaml"    "/scripts/crossplane-gcp-example-bucket.yaml"    "feat: add GCP GCS bucket example"

echo "  Seed files pushed."
# ── 4. Obtain runner registration token ─────────────────────────────────────
echo "=== [4] Obtaining runner registration token ==="
RUNNER_TOKEN=$(curl -sf "${GITEA_URL}/api/v1/admin/runners/registration-token" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" | jq -r '.token')
echo "  Runner token obtained."
# ── 5. Create Gitea token for ArgoCD ───────────────────────────────────────
echo "=== [5] Creating Gitea token for ArgoCD ==="
curl -s -X DELETE "${GITEA_URL}/api/v1/users/${GITEA_USER}/tokens/argocd-token" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" > /dev/null || true
GITEA_TOKEN=$(curl -sf -X POST "${GITEA_URL}/api/v1/users/${GITEA_USER}/tokens" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" \
  -H "Content-Type: application/json" \
  -d '{"name":"argocd-token","scopes":["read:repository","write:repository","read:admin"]}' | jq -r '.sha1')
REPO_URL="http://${RELEASE_NAME}-gitea-http.${NS}.svc.cluster.local:3000/${GITEA_USER}/clusterfactory-demo.git"
echo "  Gitea token created."
# ── 5b. Patch Gitea ROOT_URL ─────────────────────────────────────────────────
echo "=== [5b] Patching Gitea ROOT_URL ==="
curl -sf -X PUT "${GITEA_URL}/api/v1/admin/settings" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" \
  -H "Content-Type: application/json" \
  -d "{\"app_url\":\"${GITEA_ROOT_URL}\"}" > /dev/null || true
echo "  Gitea ROOT_URL set to ${GITEA_ROOT_URL}."
# ── 6. Create Harbor project ────────────────────────────────────────────────
echo "=== [6] Creating Harbor project ==="
curl -s -X POST "${HARBOR_URL}/api/v2.0/projects" \
  -u "admin:${HARBOR_PASSWORD}" \
  -H "Content-Type: application/json" \
  -d '{"project_name":"clusterfactory","public":true,"metadata":{"public":"true"}}' \
  > /dev/null || echo "  (project may already exist)"
# Patch Harbor externalURL so UI pull commands reference the correct host
curl -sf -X PUT "${HARBOR_URL}/api/v2.0/configurations" \
  -u "admin:${HARBOR_PASSWORD}" \
  -H "Content-Type: application/json" \
  -d "{\"external_url\":\"${HARBOR_EXT_URL}\"}" > /dev/null || true
echo "  Harbor externalURL set to ${HARBOR_EXT_URL}."
# ── 7. Configure OpenBao ────────────────────────────────────────────────────
echo "=== [7] Configuring OpenBao ==="
curl -s -X POST "${OPENBAO_ADDR}/v1/sys/auth/kubernetes" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{"type":"kubernetes"}' > /dev/null || echo "  (k8s auth may already be enabled)"
curl -sf -X POST "${OPENBAO_ADDR}/v1/auth/kubernetes/config" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{"kubernetes_host":"https://kubernetes.default.svc"}' > /dev/null
curl -sf -X PUT "${OPENBAO_ADDR}/v1/sys/policies/acl/clusterfactory-reader" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{"policy":"path \"secret/data/*\" { capabilities = [\"read\"] }\npath \"secret/metadata/*\" { capabilities = [\"read\", \"list\"] }"}' > /dev/null
curl -sf -X POST "${OPENBAO_ADDR}/v1/auth/kubernetes/role/clusterfactory-reader" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"bound_service_account_names\":[\"*\"],\"bound_service_account_namespaces\":[\"${NS}\"],\"policies\":[\"clusterfactory-reader\"],\"ttl\":\"1h\"}" > /dev/null
echo "  OpenBao configured."
# ── 8. Store Harbor credentials in OpenBao ─────────────────────────────────
echo "=== [8] Storing Harbor creds in OpenBao ==="
curl -sf -X POST "${OPENBAO_ADDR}/v1/secret/data/harbor" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"data\":{\"username\":\"admin\",\"password\":\"${HARBOR_PASSWORD}\",\"url\":\"${HARBOR_URL}\"}}" \
  > /dev/null
echo "  Harbor credentials stored at secret/harbor."
# ── 9. Store ArgoCD credentials in OpenBao ──────────────────────────────────
echo "=== [9] Storing ArgoCD creds in OpenBao ==="
ARGOCD_PASS=$(kubectl get secret argocd-initial-admin-secret \
  -n "${NS}" -o jsonpath='{.data.password}' 2>/dev/null | base64 -d)
curl -sf -X POST "${OPENBAO_ADDR}/v1/secret/data/argocd" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"data\":{\"username\":\"admin\",\"password\":\"${ARGOCD_PASS}\"}}" \
  > /dev/null
echo "  ArgoCD credentials stored at secret/argocd."
# ── 10. Create Headlamp admin token ─────────────────────────────────────────
echo "=== [10] Creating Headlamp access token ==="
kubectl create serviceaccount headlamp-admin -n kube-system 2>/dev/null || true
kubectl create clusterrolebinding headlamp-admin \
  --clusterrole=cluster-admin \
  --serviceaccount=kube-system:headlamp-admin 2>/dev/null || true
HEADLAMP_TOKEN=$(kubectl create token headlamp-admin -n kube-system --duration=8760h)
curl -sf -X POST "${OPENBAO_ADDR}/v1/secret/data/headlamp" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"data\":{\"token\":\"${HEADLAMP_TOKEN}\",\"url\":\"http://localhost:4466\"}}" \
  > /dev/null
echo "  Headlamp token stored at secret/headlamp."
# ── 11. Store KUBECONFIG in Gitea Actions secrets ───────────────────────────
echo "=== [11] Storing KUBECONFIG as Gitea Actions secret ==="
# Read the kubeconfig from the pre-install Secret created by bootstrap.sh,
# then patch the API server URL based on the detected environment so that
# in-cluster runners can reach the API server.
RAW_KUBECONFIG=$(kubectl get secret "${KUBECONFIG_SECRET}" -n "${NS}" \
  -o jsonpath='{.data.kubeconfig}' | base64 -d)

if [ "$CLUSTER_ENV" = "docker-desktop" ] || [ "$CLUSTER_ENV" = "local" ]; then
  # Runners in pods cannot reach 127.0.0.1 or localhost — patch to host alias.
  PATCHED_KUBECONFIG=$(echo "$RAW_KUBECONFIG" \
    | sed 's|https://127\.0\.0\.1:|https://kubernetes.docker.internal:|g' \
    | sed 's|https://localhost:|https://kubernetes.docker.internal:|g')
else
  # On remote clusters the API server URL is already routable from pods.
  PATCHED_KUBECONFIG="$RAW_KUBECONFIG"
fi

KUBECONFIG_B64=$(echo "$PATCHED_KUBECONFIG" | base64 -w0)
# Create repo-level Actions secret
_gitea_secret() {
  local name="$1"
  local value="$2"
  curl -sf -X PUT "${GITEA_URL}/api/v1/repos/${GITEA_USER}/clusterfactory-demo/actions/secrets/${name}" \
    -u "${GITEA_USER}:${GITEA_PASSWORD}" \
    -H "Content-Type: application/json" \
    -d "{\"data\":\"${value}\"}" > /dev/null \
    && echo "  secret ${name} stored" || echo "  (${name} store failed)"
}
_gitea_secret "KUBECONFIG_B64" "${KUBECONFIG_B64}"
echo "  Gitea Actions secrets stored."
echo "  Add AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY, AZURE_CREDENTIALS_JSON,"
echo "  GCP_CREDENTIALS_JSON / GCP_PROJECT_ID via Gitea UI before running configure-cloud."

# ── 12. Write handoff Secret (Phase 2 → Phase 3) ───────────────────────────
echo "=== [12] Writing clusterfactory-wiring-tokens ==="
kubectl create secret generic clusterfactory-wiring-tokens \
  --namespace "${NS}" \
  --from-literal=RUNNER_TOKEN="${RUNNER_TOKEN}" \
  --from-literal=GITEA_TOKEN="${GITEA_TOKEN}" \
  --from-literal=REPO_URL="${REPO_URL}" \
  --from-literal=HARBOR_URL="${HARBOR_URL}" \
  --from-literal=HARBOR_PASSWORD="${HARBOR_PASSWORD}" \
  --from-literal=OPENBAO_TOKEN="${OPENBAO_TOKEN}" \
  --from-literal=OPENBAO_ADDR="${OPENBAO_ADDR}" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "=== init complete ==="
