#!/bin/sh
# gitea-init.sh — Phase 2 init script
# Generated by wirectl on 2026-03-22.
# Components: Harbor, Gitea, OpenBao, Crossplane, ArgoCD
#
# Runs inside the init Job (hook weight 0).
# Writes clusterfactory-wiring-tokens Secret at the end (handoff to Phase 3).

set -e
apk add -q jq

GITEA_URL="http://${RELEASE_NAME}-gitea-http.${NS}.svc.cluster.local:3000"
GITEA_USER="${GITEA_USER}"
GITEA_PASSWORD="${GITEA_PASSWORD}"
HARBOR_URL="http://${RELEASE_NAME}-harbor-core.${NS}.svc.cluster.local"
HARBOR_PASSWORD="${HARBOR_PASSWORD}"
OPENBAO_ADDR="http://${RELEASE_NAME}-openbao.${NS}.svc.cluster.local:8200"
OPENBAO_TOKEN="${OPENBAO_TOKEN}"

# ── 1. Wait for Gitea ──────────────────────────────────────────────────────
echo "=== [1] Waiting for Gitea ==="
for i in $(seq 1 60); do
  curl -sf "${GITEA_URL}/api/healthz" > /dev/null 2>&1 && { echo "Gitea ready"; break; }
  echo "  [$i/60] not ready, retrying..."
  sleep 5
done
# ── 2. Create demo repo ────────────────────────────────────────────────────
echo "=== [2] Creating demo repo ==="
curl -sf -X POST "${GITEA_URL}/api/v1/user/repos" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" \
  -H "Content-Type: application/json" \
  -d '{"name":"clusterfactory-demo","description":"clusterfactory demo repo","auto_init":true,"default_branch":"main"}' \
  > /dev/null || echo "  (repo may already exist)"
# ── 3. Push seed files ──────────────────────────────────────────────────────
echo "=== [3] Pushing seed files to demo repo ==="
_push_file() {
  local repo_path="$1"
  local local_path="$2"
  local msg="$3"
  local content
  content=$(base64 -w0 "${local_path}")
  curl -sf -X POST "${GITEA_URL}/api/v1/repos/${GITEA_USER}/clusterfactory-demo/contents/${repo_path}" \
    -u "${GITEA_USER}:${GITEA_PASSWORD}" \
    -H "Content-Type: application/json" \
    -d "{\"message\":\"${msg}\",\"content\":\"${content}\"}" \
    > /dev/null || echo "  (${repo_path} may already exist)"
}

# CI workflow
_push_file ".gitea/workflows/ci.yaml" "/scripts/ci.yaml" "feat: add CI workflow"

# Crossplane configure-cloud workflow (flat key name from ConfigMap)
_push_file ".gitea/workflows/configure-cloud.yaml" "/scripts/crossplane-configure-cloud.yaml" "feat: add configure-cloud workflow"

# Crossplane providers in deploy/ (ArgoCD syncs these automatically)
_push_file "deploy/crossplane/provider-aws.yaml"   "/scripts/crossplane-provider-aws.yaml"   "feat: add AWS Crossplane provider"
_push_file "deploy/crossplane/provider-azure.yaml" "/scripts/crossplane-provider-azure.yaml" "feat: add Azure Crossplane provider"
_push_file "deploy/crossplane/provider-gcp.yaml"   "/scripts/crossplane-provider-gcp.yaml"   "feat: add GCP Crossplane provider"

# Crossplane ProviderConfig templates + examples
_push_file "crossplane/aws/providerconfig.yaml"    "/scripts/crossplane-aws-providerconfig.yaml"    "feat: add AWS ProviderConfig template"
_push_file "crossplane/aws/credentials.conf"       "/scripts/crossplane-aws-credentials.conf"       "feat: add AWS credentials template"
_push_file "crossplane/aws/example-bucket.yaml"    "/scripts/crossplane-aws-example-bucket.yaml"    "feat: add AWS S3 bucket example"
_push_file "crossplane/azure/providerconfig.yaml"  "/scripts/crossplane-azure-providerconfig.yaml"  "feat: add Azure ProviderConfig template"
_push_file "crossplane/azure/credentials.json"     "/scripts/crossplane-azure-credentials.json"     "feat: add Azure credentials template"
_push_file "crossplane/azure/example-storage.yaml" "/scripts/crossplane-azure-example-storage.yaml" "feat: add Azure storage example"
_push_file "crossplane/gcp/providerconfig.yaml"    "/scripts/crossplane-gcp-providerconfig.yaml"    "feat: add GCP ProviderConfig template"
_push_file "crossplane/gcp/credentials.json"       "/scripts/crossplane-gcp-credentials.json"       "feat: add GCP credentials template"
_push_file "crossplane/gcp/example-bucket.yaml"    "/scripts/crossplane-gcp-example-bucket.yaml"    "feat: add GCP GCS bucket example"

echo "  Seed files pushed."
# ── 4. Obtain runner registration token ─────────────────────────────────────
echo "=== [4] Obtaining runner registration token ==="
RUNNER_TOKEN=$(curl -sf "${GITEA_URL}/api/v1/admin/runners/registration-token" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" | jq -r '.token')
echo "  Runner token obtained."
# ── 5. Create Gitea token for ArgoCD ───────────────────────────────────────
echo "=== [5] Creating Gitea token for ArgoCD ==="
curl -s -X DELETE "${GITEA_URL}/api/v1/users/${GITEA_USER}/tokens/argocd-token" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" > /dev/null || true
GITEA_TOKEN=$(curl -sf -X POST "${GITEA_URL}/api/v1/users/${GITEA_USER}/tokens" \
  -u "${GITEA_USER}:${GITEA_PASSWORD}" \
  -H "Content-Type: application/json" \
  -d '{"name":"argocd-token","scopes":["read:repository","write:repository","read:admin"]}' | jq -r '.sha1')
REPO_URL="http://${RELEASE_NAME}-gitea-http.${NS}.svc.cluster.local:3000/${GITEA_USER}/clusterfactory-demo.git"
echo "  Gitea token created."
# ── 6. Wait for Harbor + create project ─────────────────────────────────────
echo "=== [6] Waiting for Harbor ==="
for i in $(seq 1 120); do
  curl -sf -u "admin:${HARBOR_PASSWORD}" "${HARBOR_URL}/api/v2.0/ping" > /dev/null 2>&1 \
    && { echo "Harbor ready"; break; }
  echo "  [$i/120] not ready..."
  sleep 5
done
curl -s -X POST "${HARBOR_URL}/api/v2.0/projects" \
  -u "admin:${HARBOR_PASSWORD}" \
  -H "Content-Type: application/json" \
  -d '{"project_name":"clusterfactory","public":true,"metadata":{"public":"true"}}' \
  > /dev/null || echo "  (project may already exist)"
# ── 7. Configure OpenBao ────────────────────────────────────────────────────
echo "=== [7] Configuring OpenBao ==="
for i in $(seq 1 30); do
  curl -sf "${OPENBAO_ADDR}/v1/sys/health" > /dev/null 2>&1 && { echo "OpenBao ready"; break; }
  echo "  [$i/30] not ready..."
  sleep 5
done
curl -s -X POST "${OPENBAO_ADDR}/v1/sys/auth/kubernetes" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{"type":"kubernetes"}' > /dev/null || echo "  (k8s auth may already be enabled)"
curl -sf -X POST "${OPENBAO_ADDR}/v1/auth/kubernetes/config" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{"kubernetes_host":"https://kubernetes.default.svc"}' > /dev/null
curl -sf -X PUT "${OPENBAO_ADDR}/v1/sys/policies/acl/clusterfactory-reader" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{"policy":"path \"secret/data/*\" { capabilities = [\"read\"] }\npath \"secret/metadata/*\" { capabilities = [\"read\", \"list\"] }"}' > /dev/null
curl -sf -X POST "${OPENBAO_ADDR}/v1/auth/kubernetes/role/clusterfactory-reader" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"bound_service_account_names\":[\"*\"],\"bound_service_account_namespaces\":[\"${NS}\"],\"policies\":[\"clusterfactory-reader\"],\"ttl\":\"1h\"}" > /dev/null
echo "  OpenBao configured."
# ── 8. Store Harbor credentials in OpenBao ─────────────────────────────────
echo "=== [8] Storing Harbor creds in OpenBao ==="
curl -sf -X POST "${OPENBAO_ADDR}/v1/secret/data/harbor" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"data\":{\"username\":\"admin\",\"password\":\"${HARBOR_PASSWORD}\",\"url\":\"${HARBOR_URL}\"}}" \
  > /dev/null
echo "  Harbor credentials stored at secret/harbor."
# ── 9. Store ArgoCD credentials in OpenBao ──────────────────────────────────
echo "=== [9] Storing ArgoCD creds in OpenBao ==="
for i in $(seq 1 30); do
  ARGOCD_PASS=$(kubectl get secret argocd-initial-admin-secret \
    -n "${NS}" -o jsonpath='{.data.password}' 2>/dev/null | base64 -d)
  [ -n "${ARGOCD_PASS}" ] && break
  echo "  [$i/30] waiting for ArgoCD admin secret..."
  sleep 5
done
curl -sf -X POST "${OPENBAO_ADDR}/v1/secret/data/argocd" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"data\":{\"username\":\"admin\",\"password\":\"${ARGOCD_PASS}\"}}" \
  > /dev/null
echo "  ArgoCD credentials stored at secret/argocd."
# ── 10. Create Headlamp admin token ─────────────────────────────────────────
echo "=== [10] Creating Headlamp access token ==="
kubectl create serviceaccount headlamp-admin -n kube-system 2>/dev/null || true
kubectl create clusterrolebinding headlamp-admin \
  --clusterrole=cluster-admin \
  --serviceaccount=kube-system:headlamp-admin 2>/dev/null || true
HEADLAMP_TOKEN=$(kubectl create token headlamp-admin -n kube-system --duration=8760h)
curl -sf -X POST "${OPENBAO_ADDR}/v1/secret/data/headlamp" \
  -H "X-Vault-Token: ${OPENBAO_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"data\":{\"token\":\"${HEADLAMP_TOKEN}\",\"url\":\"http://localhost:4466\"}}" \
  > /dev/null
echo "  Headlamp token stored at secret/headlamp."
# ── 11. Store KUBECONFIG in Gitea Actions secrets ───────────────────────────
echo "=== [11] Storing KUBECONFIG as Gitea Actions secret ==="
# Patch server URL for docker-desktop so in-cluster runners can reach the API
KUBECONFIG_B64=$(kubectl config view --minify --flatten \
  | sed 's|https://127.0.0.1:|https://kubernetes.docker.internal:|g' \
  | sed 's|https://localhost:|https://kubernetes.docker.internal:|g' \
  | base64 -w0)
# Create repo-level Actions secret
_gitea_secret() {
  local name="$1"
  local value="$2"
  curl -sf -X PUT "${GITEA_URL}/api/v1/repos/${GITEA_USER}/clusterfactory-demo/actions/secrets/${name}" \
    -u "${GITEA_USER}:${GITEA_PASSWORD}" \
    -H "Content-Type: application/json" \
    -d "{\"data\":\"${value}\"}" > /dev/null \
    && echo "  secret ${name} stored" || echo "  (${name} store failed)"
}
_gitea_secret "KUBECONFIG_B64" "${KUBECONFIG_B64}"
echo "  Gitea Actions secrets stored."
echo "  Add AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY, AZURE_CREDENTIALS_JSON,"
echo "  GCP_CREDENTIALS_JSON / GCP_PROJECT_ID via Gitea UI before running configure-cloud."

# ── 12. Write handoff Secret (Phase 2 → Phase 3) ───────────────────────────
echo "=== [12] Writing clusterfactory-wiring-tokens ==="
kubectl create secret generic clusterfactory-wiring-tokens \
  --namespace "${NS}" \
  --from-literal=RUNNER_TOKEN="${RUNNER_TOKEN}" \
  --from-literal=GITEA_TOKEN="${GITEA_TOKEN}" \
  --from-literal=REPO_URL="${REPO_URL}" \
  --from-literal=HARBOR_URL="${HARBOR_URL}" \
  --from-literal=HARBOR_PASSWORD="${HARBOR_PASSWORD}" \
  --from-literal=OPENBAO_TOKEN="${OPENBAO_TOKEN}" \
  --from-literal=OPENBAO_ADDR="${OPENBAO_ADDR}" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "=== init complete ==="
