{{- if and .Values.cockpit.enabled .Values.cockpit.basicAuth.enabled .Values.cockpit.basicAuth.htpasswd }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cockpit-auth
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  auth: {{ .Values.cockpit.basicAuth.htpasswd | b64enc }}
{{- end }}
