{{- if .Values.runner.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runner-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  config.yaml: |
    runner:
      labels:
        - "ubuntu-latest:host"
    container:
      valid_volumes: []
    host:
      workdir_parent: /tmp/act-runner
{{- end }}
