{{- if .Values.runner.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-runner-prepull
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gitea-runner-prepull
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea-runner-prepull
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea-runner-prepull
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: prepull
          image: {{ .Values.runner.image }}
          imagePullPolicy: IfNotPresent
          command: ["true"]
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.1
          resources:
            requests:
              cpu: 1m
              memory: 4Mi
            limits:
              cpu: 10m
              memory: 8Mi
{{- end }}
