{{- if .Values.runner.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-runner-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    log:
      level: info
    runner:
      file: /data/.runner
      capacity: 2
      fetch_interval: 2s
      fetch_timeout: 5s
      labels: []
    cache:
      enabled: false
    container:
      network: {{ if eq .Values.runner.mode "dind" }}"host"{{ else }}""{{ end }}
    host:
      workdir_parent: /tmp/act_runner_work
{{- end }}
