apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-wire
  labels:
    {{- include "clusterfactory.labels" . | nindent 4 }}
    app.kubernetes.io/component: wire
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-wire
  labels:
    {{- include "clusterfactory.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  # Read jenkins admin password from secret.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: [{{ include "clusterfactory.giteaAdminSecret" . | quote }}, {{ include "clusterfactory.jenkinsAdminSecret" . | quote }}]
  # Upsert runner registration token secret and result configmap.
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch", "update"]
    resourceNames: ["{{ .Release.Name }}-runner-reg-token"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch", "update"]
    resourceNames: ["{{ .Release.Name }}-wire-result"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-wire
  labels:
    {{- include "clusterfactory.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-wire
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-wire
  apiGroup: rbac.authorization.k8s.io
