apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wire-script
  labels:
    {{- include "clusterfactory.labels" . | nindent 4 }}
    app.kubernetes.io/component: wire
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  wire.sh: |
{{ .Files.Get "files/wire.sh" | indent 4 }}
