pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: shell
      image: alpine:3.20
      command: ["cat"]
      tty: true
'''
        }
    }
    stages {
        stage('Hello') {
            steps {
                container('shell') {
                    sh 'echo "ClusterFactory bootstrap pipeline running on $(hostname)"'
                    sh 'echo "Build: ${BUILD_NUMBER}"'
                    sh 'echo "Job: ${JOB_NAME}"'
                }
            }
        }
        stage('Verify') {
            steps {
                container('shell') {
                    sh 'echo "Pipeline OK"'
                }
            }
        }
    }
}
