apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-properties
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cf-nexus.labels" . | nindent 4 }}
data:
  nexus.properties: |
    {{- range $k, $v := .Values.properties }}
    {{ $k }}={{ $v }}
    {{- end }}
